Max/truncate and copy for s3
rhinogram/rhinocloud-sdk pull request #4
Opened 2018-10-02 17:34 UTC by maxwellsmart84

This adds copy s3 files and copy directory.  This also solves the 1000 s3 key issue with some recursive magic.

2018-10-02 17:40 UTC, rogersgt requested changes
Just update the error messages being thrown and I think this all looks good to me. Nice job 👍

2018-10-02 17:40 UTC, rogersgt commented on library/s3/index.js
> +      throw new Error(`moveS3File() requires parameters properties: sourceBucket, s3SourceFile, s3DestinationFile, and destinationBucket`);
Error should say `copyS3File()`

2018-10-02 17:40 UTC, rogersgt commented on library/s3/index.js
> +      throw new Error(`moveS3Directory() requires parameters: sourceBucket, s3SourceDirectory, destinationBucket, and s3DestinationDirectory`);
Error should say `copyS3Directory()`

2018-10-03 19:28 UTC, maxwellsmart84 commented
going to add delete and delete versions for this.

2018-10-08 15:57 UTC, closed without merging