Max/truncate copy and delete for s3
rhinogram/rhinocloud-sdk pull request #5
Opened 2018-10-08 15:58 UTC by maxwellsmart84

This adds hard delete methods for S3, this also adds copy methods as well as imports rhinolint into the repo.

2018-10-08 19:03 UTC, rogersgt requested changes

2018-10-08 19:03 UTC, rogersgt commented on library/s3/index.js
> +      const mappedKeys = keyObjects.map((k) => { return (k.Key); }).filter((k) => { return !excludedFiles.includes(k); });
Doing an inline arrow function is a return statement, so `(k) => k.Key` is the same as `(k) => { return k.Key; }`

2018-10-08 19:03 UTC, rogersgt commented on library/s3/index.js
> +          const keyVersionMap = keyVersionArray.map((k) => { return { Key: k.Key, VersionId: k.VersionId }; }).filter((k) => { return !excludedFiles.includes(k); });
See comment above.

2018-10-08 19:03 UTC, rogersgt commented on library/s3/index.js
> +      const keyVersionMap = keyVersionObjects.map((k) => { return { Key: k.Key, VersionId: k.VersionId }; }).filter((k) => { return !excludedFiles.includes(k); });
Same comment as above.

2018-10-08 19:03 UTC, rogersgt commented on library/s3/toolbox/file.tools.js
> +  const filtered = files.filter((f) => { return !excludeFiles.includes(f); });
Ditto.

2018-10-08 19:03 UTC, rogersgt commented on package.json
> +  "version": "1.0.82",
Could this be 1.9 since we are adding a bunch of functionality and we have already added different credentials config option?

2018-10-08 19:03 UTC, rogersgt commented on package.json
> +  "devDependencies": {
Should we do `0.0.x` instead of `^`?

2018-10-09 13:19 UTC, maxwellsmart84 commented
@rogersgt  those returns were added because of rhinolint rule - i know its the same thing but our linter apparently doesn't allow it.

2018-10-09 14:19 UTC, rogersgt commented
I'll approve this with the intention of us fixing the linter rule in `eslint-config-rhinogram`

2018-10-09 14:19 UTC, rogersgt approved these changes

2018-10-09 14:19 UTC, merged